# Generated by Django 5.2.6 on 2025-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('offer_price', models.FloatField(default=0.0)),
                ('offer_numberOfPerson', models.IntegerField(default=0)),
                ('offer_stock', models.IntegerField(default=0)),
                ('offer_description', models.TextField(blank=True)),
            ],
        ),
    ]
