# Generated by Django 5.2.6 on 2025-10-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
