# Generated by Django 5.2.6 on 2025-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_ordered_cart_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
