# Generated by Django 5.2.6 on 2025-10-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_offer_offer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
    ]
