# Generated by Django 5.2.6 on 2025-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_ordered_cart_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generated_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
