# Generated by Django 5.2.6 on 2025-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_generated_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='generated_qr_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
