# Generated by Django 5.2.6 on 2025-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='c4e4aada952898cfb52ada3f9eafe52c', max_length=255),
        ),
    ]
