# Generated by Django 5.2.6 on 2025-10-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='836e4ee0b006afcaa01817e139356257', max_length=255),
        ),
    ]
