# Generated by Django 5.2.6 on 2025-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='57b808923109412bf24287ff8e789a28', max_length=255),
        ),
    ]
