# Generated by Django 5.2.6 on 2025-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='786c03977e68780c12e9cc4e00f6d273', max_length=255),
        ),
    ]
