# Generated by Django 5.2.6 on 2025-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='3a5b7cb8b425735b07e5823ee7fbb211', max_length=255),
        ),
    ]
