# Generated by Django 5.2.6 on 2025-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='4407118edf16feeeb94cd2af94c80b5c', max_length=255),
        ),
    ]
