# Generated by Django 5.2.6 on 2025-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='6b70cbc4b79ac6ae1a949c126c0060e4', max_length=255),
        ),
    ]
