# Generated by Django 5.2.6 on 2025-10-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(blank=True, default='29e488efd9f1746eb7cf8c940c562bfb', max_length=255),
        ),
    ]
